baseURL = 'https://OwOss.github.io/my-Blowfish/'
languageCode = 'en-us'
title = 'OwOss'
theme = "blowfish"
#sectionPagesMenu = "main"

[params]
math = true
copyright = "© Wade Wang"

[params.author]
name = "OwOss"
image = "img/blowfish_logo_transparent.png"
headline = "A Mortal"
bio = "一行代码写一天，逻辑理顺笑开颜！"
#links = [{ twitter = "https://twitter.com/username" }]

